spring:
  application:
    name: fraudshield-genai

fraudshield:
  gemini:
    project-id: ${GCP_PROJECT_ID:qwiklabs-gcp-01-dc26193870df}
    location: ${GCP_LOCATION:us-central1}
    model-name: ${GEMINI_MODEL:gemini-2.5-flash}
    max-output-tokens: 300
    temperature: 0.2

server:
  port: 8080
